### ISSUE TITLE
Data duplication in FEVM event extraction

### ISSUE THREAD

**Issue by beng-starboard** [starboard-ventures/fevm-event-tracing#12]
There is a significant amount of data duplication in the `fevm_event` table. 

```
select 
  height,
  float(get_json_object(note, '$.Amount'))*1e-18 as received_fil,
  get_json_object(note, '$.AgentAddr') as agent_address
from fvm_mainnet.fevm_event 
where event_name='OnNewFundReceived(uint256,address)'
and get_json_object(note, '$.AgentAddr') = '0x81e78903376cc2D6206B76330851f90Cf82baE2f'
order by height
```

**Comment by Terryhung** [comment]
In code: https://github.com/starboard-ventures/fevm-event-tracing/blob/main/internal/busi/core/instancejob/common/common.go#L88

We found that for each `fevm_event` will be same exclude of `note` field: https://github.com/starboard-ventures/fevm-event-tracing/blob/main/internal/busi/core/instancejob/common/common.go#L106. If even the note data is the same, we won't be able to distinguish the differences between the two data.

**Comment by Terryhung** [comment]
More detail in Slack: https://starboardlab.slack.com/archives/C04844LP3JM/p1719203057192369
